config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root "expenses#index"
  put 'expenses/:id/approve', to: 'expenses#approve', as: 'approve'
  put 'expenses/:id/reject', to: 'expenses#reject', as: 'reject'
  get 'expenses/stats', to: 'expenses#stats'
  resources :expenses
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/status.rb
module Status
    extend ActiveSupport::Concern
    VALID_STATUS = ['pending','approved','rejected']
    included do
        validates :status, inclusion: {in: VALID_STATUS}
    end

    def approve
        self.status = 'approved'
        self.save
    end
    def reject
        self.status = 'rejected'
        self.save
    end
    def approved?
        status == 'approved'
    end

    def rejected?
        status == 'rejected'
    end

    def pending?
        status == 'pending'
    end

end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :expenses
end

app/models/expense.rb
class Expense < ApplicationRecord
  include Status
  belongs_to :employee

  def self.sum_amount_per_month
    select("DATE_TRUNC('month', date) AS month, SUM(amount) AS total_amount")
      .group("month")
      .order("month")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
    def index
        
        @names = Employee.pluck(:name)
        @expense = Expense.new
        @filter = params[:filter]
        if @filter == 'all' || @filter.nil?
            @expenses = Expense.all
        elsif @filter == 'approved'
            @expenses = Expense.where(status: 'approved')
        elsif @filter == 'pending'
            @expenses = Expense.where(status: 'pending')
        elsif @filter == 'rejected'
            @expenses = Expense.where(status: 'rejected')
        end
    end
    def create
        
        @employee = Employee.find_by(name: expense_params[:claimer])
        @employee.expenses.create(date: expense_params[:date], description: expense_params[:description], amount: expense_params[:amount])
        redirect_to root_path
        
    end

    def update
        @expense = Expense.find(params[:id])
        @expense.update(expense_update_params)
        redirect_to expenses_path
    end

    def destroy
        @expense = Expense.find(params[:id])
        @expense.destroy
        redirect_to expenses_path
    end

    def approve
        @expense = Expense.find(params[:id])
        @expense.approve
        redirect_to expenses_path
    end
    def reject
        @expense = Expense.find(params[:id])
        @expense.reject
        redirect_to expenses_path

    end

    def stats
        @expenses_per_month = Expense.sum_amount_per_month.map do |exp|
            {
              label: exp.month.strftime("%B %Y"), # Format month as readable
              value: exp.total_amount
            }
        end
        
          # Prepare data for Chartkick
        @expenses_per_month_chart_data = @expenses_per_month.map do |exp|
            [exp[:label], exp[:value]]
        end
    end

    private
    def expense_params
        params.require(:expense).permit(:claimer,:date,:description,:amount)
        
    end
    def expense_update_params
        params.require(:expense).permit(:date,:description,:amount) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_exrecaps.html.erb
<table class='recap-tab'>
  <thead>
    <tr class='tr-header'>
        <th>Status </th>
        <th>Claimer </th>     
        <th>Description </th>
        <th>Date </th>
        <th>Amount </th>
        <th>Actions </th>
    </tr>
  </thead>
 <% expenses.each do |expense| %>
  <%= render "form", locals={"action_name": "Edit", "expense": expense, "all_names": names} %>
  <tr>
    <td><button class='st-bt'  style="
    background-color: 
      <%= case expense.status
            when 'pending' then 'rgb(214,186,88)'
            when 'rejected' then 'rgb(214,77,71)'
            when 'approved' then 'rgb(30,185,128)'
            else 'gray'
          end %>;" disabled><%= expense.status%> </button></td>
    <td><%=expense.employee.name %></td>
    <td class='desc'><%=expense.description %></td>
    <td><%=expense.date %></td>
    <td><%=expense.amount %>€</td>
    <td class="bt-wrapper">
        <%= button_to 'APPROVE',approve_path(expense),method: :put,  class:"action-bt app-bt" %>
        <%= button_to 'REJECT',reject_path(expense),method: :put, class:"action-bt rej-bt" %>
        <button class="action-bt edit-bt"> UPDATE </button>
        <%= button_to 'DELETE',expense_path(expense),method: :delete, class:"action-bt del-bt" %>
    </td>
  </tr>
  
  <% end %>
 </table>

app/views/expenses/_form.html.erb
<div class='<%= case action_name 
            when "New" then "new-form"
            else "edit-form"
          end %>'>
    <h2> <%=action_name %> Expense Request</h2>
    <%= form_with model: expense do |form| %>
        <div class='input-container'>
            <%= form.label :claimer, class:'form-label' %>
            <%= form.select :claimer, all_names,{},{class:'form-input',disabled: (action_name != 'New')} %>
        </div>
        <div class='input-container'>
            <%= form.label :date, class:'form-label' %>
            <%= form.date_field :date, class:'form-input' %>
        </div>
        <div class='input-container'>
            <%= form.label :description, class:'form-label' %>
            <%= form.text_area :description, class:'form-input' %>
        </div>
        <div class='input-container'>
            <%= form.label :amount, class:'form-label' %>
            <%= form.number_field :amount, class:'form-input' %>
        </div>
        <div class='btn-wrapper'>
            <%= form.submit %>
        </div>

    <% end %>
    <button class='cancel-bt'> CANCEL </button>
</div>

app/views/expenses/index.html.erb
<div class='container'>
    

    <div class="side-bar">
        <h2 class='company-name'>Titus Inc </h2>
        <p class="seperator extra-margin"> . . . . . </p>
        <%= link_to 'ALL EXPENSES', root_path(filter: 'all'), class:"option filter" %>
        <%= link_to 'PENDING APPROVAL', root_path(filter: 'pending'), class:"option filter" %>
        <%= link_to 'APPROVED EXPENSES', root_path(filter: 'approved'), class:"option filter" %>
        <%= link_to 'REJECTED EXPENSES', root_path(filter: 'rejected'), class:"option filter" %>
        <p class="seperator"> . . . . . </p>
        <%= link_to 'STATS', expenses_stats_path, class:"option filter" %>
    </div>
    <div class="dash">
        <div class="dash-header">
            <h1 >Expense Request Dashboard</h1>
            <button id='add-request'> <%= image_tag("icon.png") %> NEW REQUETE </>
        </div>
        <%= render "exrecaps", locals={"expenses": @expenses || [],"names": @names} %>
        
    </div>
    <%= render "form", locals={"action_name": "New", "expense": @expense, "all_names": @names} %>
</div>

app/views/expenses/stats.html.erb
<div class='stats-container'>
    <%= link_to image_tag("left-arrow.png"), root_path, class: 'back-icon' %>
    <h1 >Expenses Per Month</h1>
    <div class='chart-wrapper'>
        <%= bar_chart @expenses_per_month_chart_data %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Expense Claims" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", media: "all", data: { turbolinks: false } %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>